services:
  test-app:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        TEST: "true"
    volumes:
      - ./app:/app
    env_file:
      - .env.test
    depends_on:
      - test-redis
    command: >
      pytest --maxfail=1 --disable-warnings

  test-redis:
    image: redis:alpine
