name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create .env.test file from secrets
        run: |
          cat <<EOF > .env.test
          DB_NAME=${{ secrets.DB_NAME }}
          DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}
          DB_USER=${{ secrets.DB_USER }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DJANGO_ENV=test
          REDIS_URL_TEST=${{ secrets.REDIS_URL_TEST }}
          AWS_REGION=${{ secrets.AWS_REGION }}
          COGNITO_CLIENT_ID_SSM_PATH=${{ secrets.COGNITO_CLIENT_ID_SSM_PATH }}
          COGNITO_USER_POOL_ID=${{ secrets.COGNITO_USER_POOL_ID }}
          KMS_KEY_ID=${{ secrets.KMS_KEY_ID }}
          EOF
          echo "Created .env.test file"

      - name: Build and run tests with Docker Compose
        run: |
          docker compose -f docker-compose.test.yml up --build --exit-code-from test-app --abort-on-container-exit

      - name: Tear down Docker Compose
        if: always()
        run: docker compose -f docker-compose.test.yml down
